### ISSUE TITLE
Line overflow with Hack Club banners post

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/blog#16]
![screenshot from 2016-02-17 15 33 00](https://cloud.githubusercontent.com/assets/5891442/13123756/c130208c-d58b-11e5-8616-d73851754d3c.png)

**Comment by zachlatta** [comment]
Maybe we could use textboxes instead? Not sure what that'd look like in Markdown, but it's what GitHub does in their ribbon blog post: https://github.com/blog/273-github-ribbons

**Comment by jkwok91** [comment]
Markdown appears to hate textareas? Can we stick CSS on this table somehow?

**Comment by MaxWofford** [comment]
@jkwok91 Yep! Check out the blog's css files
