### ISSUE TITLE
blog.hackclub.com is currently down

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/blog#22]
I'm just getting a blank screen.

![screenshot_2016-04-17_13 48 56](https://cloud.githubusercontent.com/assets/5891442/14588898/2e4ffb42-04a3-11e6-9e2f-e6472ead471d.png)

**Comment by zachlatta** [comment]
Thanks for finding this, investigating now.

On Sun, Apr 17, 2016 at 10:49 AM, Max Wofford <notifications@github.com>
wrote:

> I'm just getting a blank screen.
>
> [image: screenshot_2016-04-17_13 48 56]
> <https://cloud.githubusercontent.com/assets/5891442/14588898/2e4ffb42-04a3-11e6-9e2f-e6472ead471d.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/blog/issues/22>
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
Just submitted #23 to fix this.

On Sun, Apr 17, 2016 at 3:03 PM, Zach Latta <zach@hackclub.com> wrote:

> Thanks for finding this, investigating now.
>
> On Sun, Apr 17, 2016 at 10:49 AM, Max Wofford <notifications@github.com>
> wrote:
>
>> I'm just getting a blank screen.
>>
>> [image: screenshot_2016-04-17_13 48 56]
>> <https://cloud.githubusercontent.com/assets/5891442/14588898/2e4ffb42-04a3-11e6-9e2f-e6472ead471d.png>
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/blog/issues/22>
>>
>
>
>
> --
> Zach Latta
> Hack Club | zach@hackclub.com
>



-- 
Zach Latta
Hack Club | zach@hackclub.com
