### ISSUE TITLE
Create "Slack Highlights" blog post for this week

### ISSUE THREAD

**Issue by zachlatta** [hackclub/blog#5]
It'd be awesome if it were in the same style of http://themacro.com/articles/2015/12/hacker-news-highlights-2/.

Couple ideas for what we could include in it:

- @hardmath123 said that he really enjoyed his conversation with @matthesby on sigfigs
- metmets (in the Slack) had his first club meeting in Estonia
- @jonleung said he really enjoyed pairing with @ZucchiniZe in a hangout this week, which was coordinated through the Slack

**Comment by MaxWofford** [comment]
Closed by https://github.com/hackclub/blog/pull/8
